# Introduction
A key feature of PorePy is that forward-mode automatic (or algorithmic) differentiation, AD, is used to linearize a system of partial differential equations. This tutorial provides a short introduction to automatic differentiation and an overview of the AD-module included in PorePy. 

Further description is provided in other tutorials: *pdes with ad*  explains how to use the module to solve (mixed-dimensional) PDEs. For an example where the AD module has been used to solve non-linear compressible flow, see the tutorial:  "compressible_flow_with_automatic_differentiation"


In [1]:
import numpy as np
import scipy.sparse as sps

from porepy.numerics.ad.forward_mode import AdArray
import porepy.numerics.ad.functions as af
import porepy as pp

# AD module
Automatic differentiation is used to compute the derivative of a function. This is achieved by augmenting variables with a field representing the derivative in addition to the value of the variable. Evaluation of a function of such variables is performed by (repeatedly) applying the chain rule while keeping track of both values and derivatives.

## Scalar variables

We initiate a variable $x = 2$ by giving a pair (val, jac) to the AdArray class. val is the value at which the function will be evaluated and jac =1 since $\frac{d x}{dx} = 1$.

In [3]:
x = AdArray(np.array([2]), sps.eye(1, 1))

We can now define a function $y=x^2 + 3$ 

In [ ]:
y = x**2 + 3

To obtain the function value and the derivative we can call .val and .jac

In [ ]:
print('y value is: ', y.val)
print('dy/dx is: ', y.jac)

y value is:  7.0
dy/dx is:  4.0


$y$ is also an AD variable as a function of $x$. We can use it to declare further functions, e.g., $h(x) = e^{y(x)}$. To take the exponential of an AdArray we need to call the exponential function found in the AD module

In [ ]:
h = af.exp(y)
print('h value is: ', h.val)
print('dh/dx is: ', h.jac)

h value is:  1096.6331584284585
dh/dx is:  4386.532633713834


If we know the value and Jacobian of $y$ we could alternatively skip initiating $x$ and initiate $y$ directly:

In [4]:
y = AdArray(np.array([7]), 4 * sps.eye(1, 1))
h = af.exp(y)
print('h value is: ', h.val)
print('dh/dx is: ', h.jac)

h value is:  [1096.63315843]
dh/dx is:    (0, 0)	4386.532633713834


## Vector variables
The AdArray class also supports arrays.

In [5]:
x = AdArray(np.array([3,2,1]), sps.diags([1,1,1]))

As for the scalar case, it is straightforward to define functions using normal Python programming. Let us declare the function
$$y(x) = \mathbf{A} x + x^2 - b$$
which has the Jacobian
$$ J_y(x) = \mathbf{A} + 2 \, \mathbf{I}\, x$$
With this notation we mean $x^2 = [x_1^2, x_2^2, x_3^2]$.

In [7]:
A = sps.csc_matrix(np.array([[3,2,1],
                             [2,6,1],
                             [2,3,4]]))
b =  AdArray(np.array([1,0,0]), sps.diags([0,0,0]))
y = A @ x  + x**2 - b

print('Analytic y value: ')
print(np.array([22, 23, 17]))
print('Analytic y Jacobian:')
print(np.array([[9,2,1],[2,10,1],[2,3,6]]),'\n')
print('Ad y value: ')
print(y.val)
print('Ad y Jacobian:')
print(y.jac.A)


Analytic y value: 
[22 23 17]
Analytic y Jacobian:
[[ 9  2  1]
 [ 2 10  1]
 [ 2  3  6]] 

Ad y value: 
[22. 23. 17.]
Ad y Jacobian:
[[ 9.  2.  1.]
 [ 2. 10.  1.]
 [ 2.  3.  6.]]


## Equations
An equation is defined by expressing it in residual form
$$y(x) = 0.$$
We can find its roots (solution) using the Newton-Rhapson scheme, which, on linearized form, reads 
$$J_y(x^{k}) (x^{k+1} - x^{k}) = - y(x^{k}).$$

In [8]:
tol = 1e-5
residuals = list()
for i in range(5): 
    x = x - sps.linalg.spsolve(y.jac, y.val)
    y = A @ x  + x**2 - b
    residuals.append(np.linalg.norm(y.val))

print(f"After five iterations, the solution is {x.val}. The residuals were ")
print(residuals)


After five iterations, the solution is [ 0.39609763 -0.11506208 -0.11506208]. The residuals were 
[5.121415047969018, 0.37208984847741916, 0.010886193063849024, 1.2643761102354224e-05, 1.7809260833326555e-11]


Conceptually, the example illustrates how equations can be solved in PorePy:
1. Define ad variables and parameters matrices
2. Combine variables and parameters into equations on residual form
3. Solve the nonlinear problem using Newton-Rhapson (or another suitable linearization method)

Extending the concept to PDEs in mixed-dimensional form only requires some additional book-keeping. Specifically, variables, parameters, etc. are defined on subdomains and interfaces of the mixed-dimensional grid as shown in the [equation definition tutorial](https://github.com/pmgbergen/porepy/blob/develop/tutorials/equation_definition.ipynb).

# What have we explored
Automatic differentiation (AD) gives access to derivatives of complex functions with minimal user effort. PorePy implements forward AD, primarily aimed at solving non-linear problems using Newton's method. The value and derivatives of an `AdArray` are contained in its attributes val and jac, respectively.