In [1]:
import numpy as np
from scipy.sparse.linalg import spsolve
import scipy.sparse as sps
import sympy
from math import pi
from time import time

import pyamg

import setup_grids

from porepy.numerics.fv import mpsa, fvutils

from porepy.params.tensor import FourthOrderTensor as stiffness
from porepy.params import bc
from porepy.viz.plot_grid import plot_grid

In [2]:
# Permeability tensor, scalar for simplicity
mu = 1
lmbda = 1

###
# This is where parameters can be modified to alter the convergence test.
# The remaining lines should 
np.random.seed(42)
base = 4
domain = np.array([1, 1])
basedim = np.array([base, base])
num_refs = 4
grid_type = 'cart'

# Analytical solution
x, y = sympy.symbols('x y')
ux = sympy.sin(x) * sympy.cos(y)
uy = sympy.sin(x) * x**2
ux_f = sympy.lambdify((x, y), ux, 'numpy')
uy_f = sympy.lambdify((x, y), uy, 'numpy')
dux_x = sympy.diff(ux, x)
dux_y = sympy.diff(ux, y)
duy_x = sympy.diff(uy, x)
duy_y = sympy.diff(uy, y)
divu = dux_x + duy_y

sxx = 2 * mu * dux_x + lmbda * divu
sxy = mu * (dux_y + duy_x)
syx = mu * (duy_x + dux_y)
syy = 2 * mu * duy_y + lmbda * divu

sxx_f = sympy.lambdify((x, y), sxx, 'numpy')
sxy_f = sympy.lambdify((x, y), sxy, 'numpy')
syx_f = sympy.lambdify((x, y), syx, 'numpy')
syy_f = sympy.lambdify((x, y), syy, 'numpy')

rhs_x = sympy.diff(sxx, x) + sympy.diff(syx, y)
rhs_y = sympy.diff(sxy, x) + sympy.diff(syy, y)
rhs_x_f = sympy.lambdify((x, y), rhs_x, 'numpy')
rhs_y_f = sympy.lambdify((x, y), rhs_y, 'numpy')

def run_convergence(grid_type, pert):
    u_err = []
    flux_err = []

    for g in setup_grids.grid_sequence(basedim, num_refs, grid_type, pert, domain=domain):
        # Reset the random seed for every grid realization.
        # This should make no difference for the convergence test, 
        # but it makes sure that we can run unit tests based on the values obtained
        # here.
        np.random.seed(42)
            
        # Permeability tensor
        mu_c = mu * np.ones(g.num_cells)
        lmbda_c = lmbda * np.ones(g.num_cells)
        k = stiffness(2, mu_c, lmbda_c)

        # Set type of boundary conditions - Dirichlet
        bound_faces = g.get_all_boundary_faces()
        bound_cond = bc.BoundaryCondition(g, bound_faces, ['dir'] * bound_faces.size)
        
        # MPFA discretization, and system matrix
        stress, bound_stress = mpsa.mpsa(g, k, bound_cond)
        div = fvutils.vector_divergence(g)
        a = div * stress
        
        # Boundary conditions
        xf = g.face_centers
        u_bound = np.zeros((g.dim, g.num_faces))
        u_bound[0, bound_faces] = ux_f(xf[0, bound_faces], xf[1, bound_faces])
        u_bound[1, bound_faces] = uy_f(xf[0, bound_faces], xf[1, bound_faces])
        
        
        # Right hand side - contribution from the solution and the boundary conditions
        xc = g.cell_centers
        rhs = np.vstack((rhs_x_f(xc[0], xc[1]), rhs_y_f(xc[0], xc[1]))) * g.cell_volumes
        b = rhs.ravel('F') - div * bound_stress * u_bound.ravel('F')

        # Solve system, derive fluxes
        u_num = spsolve(a, b)
        stress_num = stress * u_num + bound_stress * u_bound.ravel('F')

        ux_num = u_num[::2]
        uy_num = u_num[1::2]
        
        stress_x_num = stress_num[::2]
        stress_y_num = stress_num[1::2]
        # Exact solution
        ux_ex = ux_f(xc[0], xc[1])
        uy_ex = uy_f(xc[0], xc[1])
        u_ex = np.vstack((ux_ex, uy_ex))
        u_diff = np.vstack((ux_num - ux_ex, uy_num - uy_ex))
        
        sx_ex_faces = np.vstack((sxx_f(xf[0], xf[1]), sxy_f(xf[0], xf[1])))
        sy_ex_faces = np.vstack((syx_f(xf[0], xf[1]), syy_f(xf[0], xf[1])))
        
        stress_x_ex = np.sum(g.face_normals[:2] * sx_ex_faces, axis=0)
        stress_y_ex = np.sum(g.face_normals[:2] * sy_ex_faces, axis=0)
        stress_diff = np.vstack((stress_x_num - stress_x_ex, 
                                 stress_y_num - stress_y_ex))
        stress_ex = np.vstack((stress_x_ex, stress_y_ex))
        
        u_err.append(np.sqrt(np.sum(g.cell_volumes * u_diff**2)) /
                     np.sqrt(np.sum(g.cell_volumes * u_ex**2)))
        flux_err.append(np.sqrt(np.sum((g.face_areas ** g.dim) * stress_diff**2))/
                        np.sqrt(np.sum((g.face_areas ** g.dim) * stress_ex**2)))
    return u_err, flux_err


grids = ['cart', 'triangular']


u_cart_nopert, f_cart_nopert = run_convergence('cart', 0)
print('Cartesian errors - no perturbations')
print(u_cart_nopert,'displacement error')
print(f_cart_nopert,'stress error')

u_cart_pert, f_cart_pert = run_convergence('cart', 0.5)
print('Cartesian errors - perturbation 0.5')
print(u_cart_pert,'displacement error')
print(f_cart_pert,'stress error')


u_triang_nopert, f_triang_nopert = run_convergence('triangular', 0)
print('Triangular errors - no perturbations')
print(u_triang_nopert,'displacement error')
print(f_triang_nopert,'stress error')


u_triang_pert, f_triang_pert = run_convergence('triangular', 0.5)
print('Triangular errors - perturbation 0.5')
print(u_triang_pert,'displacement error')
print(f_triang_pert,'stress error')

# EK: These values were hard-coded 12.06.2017.
assert np.abs(u_cart_nopert[2] - 0.00078374466288952144) < 1e-10
assert np.abs(f_cart_nopert[2] - 0.0030273898153929924) < 1e-10
assert np.abs(u_cart_pert[2] - 0.0010317052894504846) < 1e-10
assert np.abs(f_cart_pert[2] - 0.0053879362435559708) < 1e-10


# RB: These values were hard-coded 06.09.2018. The values changed because
# the default value for eta for triangular grids was changed to 1/3
assert np.abs(u_triang_nopert[2] - 0.0005339430679082081) < 1e-10
assert np.abs(f_triang_nopert[2] - 0.005076956913423936) < 1e-10
assert np.abs(u_triang_pert[2] - 0.0006930802706380639) < 1e-10
assert np.abs(f_triang_pert[2] - 0.007100574505058305) < 1e-10

Cartesian errors - no perturbations
[0.011010878448828448, 0.0030197500225270933, 0.0007837446628904635, 0.00019841406340054548] displacement error
[0.036391713833312, 0.010752498606472382, 0.003027389815393291, 0.0008407990967767796] stress error
Cartesian errors - perturbation 0.5
[0.013141424612606898, 0.003959554975380245, 0.001031705289450405, 0.00024384620727654387] displacement error
[0.03618728579049561, 0.015764291256799894, 0.005387936243555718, 0.0020697006664011576] stress error
Triangular errors - no perturbations
[0.007499534100939774, 0.002035510853495113, 0.0005339430679082081, 0.0001366067446813222] displacement error
[0.048716801365141, 0.015930725831506523, 0.005076956913423936, 0.0016467565321741852] stress error
Triangular errors - perturbation 0.5
[0.009376925921720678, 0.0026191763163007998, 0.0006930802706380639, 0.00017435555727363358] displacement error
[0.04808796652224495, 0.019133502522555433, 0.007100574505058305, 0.00277664388741696] stress error


# Neumann boundary conditions


In [3]:
# Permeability tensor, scalar for simplicity
mu = 1
lmbda = 1

###
# This is where parameters can be modified to alter the convergence test.
# The remaining lines should 
np.random.seed(42)
base = 3
domain = np.array([1, 1])
basedim = np.array([base, base])
num_refs = 3
grid_type = 'cart'

# Analytical solution
x, y = sympy.symbols('x y')
ux = (0.5-y)**2 * sympy.sin(y) * sympy.cos(y)
uy = y * (y-1) * sympy.cosh(x)
ux_f = sympy.lambdify((x, y), ux, 'numpy')
uy_f = sympy.lambdify((x, y), uy, 'numpy')
dux_x = sympy.diff(ux, x)
dux_y = sympy.diff(ux, y)
duy_x = sympy.diff(uy, x)
duy_y = sympy.diff(uy, y)
divu = dux_x + duy_y

sxx = 2 * mu * dux_x + lmbda * divu
sxy = mu * (dux_y + duy_x)
syx = mu * (duy_x + dux_y)
syy = 2 * mu * duy_y + lmbda * divu

sxx_f = sympy.lambdify((x, y), sxx, 'numpy')
sxy_f = sympy.lambdify((x, y), sxy, 'numpy')
syx_f = sympy.lambdify((x, y), syx, 'numpy')
syy_f = sympy.lambdify((x, y), syy, 'numpy')

rhs_x = sympy.diff(sxx, x) + sympy.diff(syx, y)
rhs_y = sympy.diff(sxy, x) + sympy.diff(syy, y)
rhs_x_f = sympy.lambdify((x, y), rhs_x, 'numpy')
rhs_y_f = sympy.lambdify((x, y), rhs_y, 'numpy')

def run_convergence(grid_type, pert):
    u_err = []
    flux_err = []

    for g in setup_grids.grid_sequence(basedim, num_refs, grid_type, pert, domain=domain):
        # Reset the random seed for every grid realization.
        # This should make no difference for the convergence test, 
        # but it makes sure that we can run unit tests based on the values obtained
        # here.
        np.random.seed(42)
            
        xf = g.face_centers
        sx_ex_faces = np.vstack((sxx_f(xf[0], xf[1]), sxy_f(xf[0], xf[1])))
        sy_ex_faces = np.vstack((syx_f(xf[0], xf[1]), syy_f(xf[0], xf[1])))
        
        stress_x_ex = np.sum(g.face_normals[:2] * sx_ex_faces, axis=0)
        stress_y_ex = np.sum(g.face_normals[:2] * sy_ex_faces, axis=0)

        # Permeability tensor
        mu_c = mu * np.ones(g.num_cells)
        lmbda_c = lmbda * np.ones(g.num_cells)
        k = stiffness(2, mu_c, lmbda_c)

        # Set type of boundary conditions - Dirichlet
        n = g.nodes.max()
        # Set type of boundary conditions - Dirichlet
        top = np.ravel(np.argwhere(g.face_centers[1, :] > n - 1e-10))
        bot = np.ravel(np.argwhere(g.face_centers[1, :] < 1e-10))
        left = np.ravel(np.argwhere(g.face_centers[0, :] < 1e-10))
        right = np.ravel(np.argwhere(g.face_centers[0, :] > n - 1e-10))

        dir_faces = np.hstack((bot, top))
        neu_faces = np.hstack((left, right)) 
        bound_cond = bc.BoundaryCondition(g, dir_faces, ['dir'] * dir_faces.size)
        
        # MPFA discretization, and system matrix
        stress, bound_stress = mpsa.mpsa(g, k, bound_cond)
        div = fvutils.vector_divergence(g)
        a = div * stress
        xf = g.face_centers
        
        nfi, _, sgn = sps.find(g.cell_faces[neu_faces,:])
        
        u_bound = np.zeros((g.dim, g.num_faces))
        u_bound[0, dir_faces] = ux_f(xf[0, dir_faces], xf[1, dir_faces])
        u_bound[1, dir_faces] = uy_f(xf[0, dir_faces], xf[1, dir_faces])
        
        # When setting the Neumann boundary condition we need to flip the 
        # sign of the faces with a normal pointing inwards as it is assumed
        # that the Neumann condition is the force from the boundary on to face
        u_bound[0, neu_faces[nfi]] = stress_x_ex[neu_faces[nfi]] * (sgn)
        u_bound[1, neu_faces[nfi]] = stress_y_ex[neu_faces[nfi]] * (sgn)
        # Right hand side - contribution from the solution and the boundary conditions
        xc = g.cell_centers
        rhs = np.vstack((rhs_x_f(xc[0], xc[1]), rhs_y_f(xc[0], xc[1]))) * g.cell_volumes
        b = rhs.ravel('F') - div * bound_stress * u_bound.ravel('F')

        # Solve system, derive fluxes
        u_num = spsolve(a, b)
        stress_num = stress * u_num + bound_stress * u_bound.ravel('F')

        ux_num = u_num[::2]
        uy_num = u_num[1::2]
        
        stress_x_num = stress_num[::2]
        stress_y_num = stress_num[1::2]
        # Exact solution
        ux_ex = ux_f(xc[0], xc[1])
        uy_ex = uy_f(xc[0], xc[1])
        u_ex = np.vstack((ux_ex, uy_ex))
        u_diff = np.vstack((ux_num - ux_ex, uy_num - uy_ex))
        
        stress_diff = np.vstack((stress_x_num - stress_x_ex, 
                                 stress_y_num - stress_y_ex))
        stress_ex = np.vstack((stress_x_ex, stress_y_ex))
        
        u_err.append(np.sqrt(np.sum(g.cell_volumes * u_diff**2)) /
                     np.sqrt(np.sum(g.cell_volumes * u_ex**2)))
        flux_err.append(np.sqrt(np.sum((g.face_areas ** g.dim) * stress_diff**2))/
                        np.sqrt(np.sum((g.face_areas ** g.dim) * stress_ex**2)))
                
    return u_err, flux_err

u_cart_nopert, f_cart_nopert = run_convergence('cart', 0)
u_cart_rate = np.array(u_cart_nopert)
u_cart_rate = u_cart_rate[:-1] / u_cart_rate[1:]
f_cart_rate = np.array(f_cart_nopert)
f_cart_rate = f_cart_rate[:-1] / f_cart_rate[1:]
print('Cartesian errors - no perturbations')
print(u_cart_nopert,'displacement error')
print(u_cart_rate, 'convergence rate u^n-1 / u^n\n')
print(f_cart_nopert,'stress error')
print(f_cart_rate, 'convergence rate f^n-1 / f^n\n')

u_triang_nopert, f_triang_nopert = run_convergence('triangular', 0)
u_triang_rate = np.array(u_triang_nopert)
u_triang_rate = u_triang_rate[:-1] / u_triang_rate[1:]
f_triang_rate = np.array(f_triang_nopert)
f_triang_rate = f_triang_rate[:-1] / f_triang_rate[1:]

print('Triangular errors - no perturbations')
print(u_triang_nopert,'displacement error')
print(u_triang_rate, 'convergence rate u^n-1 / u^n\n')
print(f_triang_nopert,'stress error')
print(f_triang_rate, 'convergence rate f^n-1 / f^n')

# # EK: These values were hard-coded 12.06.2017.
assert np.abs(u_cart_nopert[2] - 0.01978509916668196) < 1e-10
assert np.abs(f_cart_nopert[2] - 0.017633923832997497) < 1e-10

# RB: These values were hard-coded 06.09.2018.
assert np.abs(u_triang_nopert[2] - 0.015475821210292553) < 1e-10
assert np.abs(f_triang_nopert[2] - 0.016373893423034032) < 1e-10

Cartesian errors - no perturbations
[0.19341322457532645, 0.05398606173752483, 0.019785099166683015] displacement error
[3.58265112 2.72862225] convergence rate u^n-1 / u^n

[0.03080448569971605, 0.022727907422006446, 0.017633923832997576] stress error
[1.35535952 1.28887408] convergence rate f^n-1 / f^n

Triangular errors - no perturbations
[0.15803686415889875, 0.04310823056510322, 0.015475821210292553] displacement error
[3.6660485  2.78552136] convergence rate u^n-1 / u^n

[0.04467366719714846, 0.02540025474312989, 0.016373893423034032] stress error
[1.75878816 1.55126543] convergence rate f^n-1 / f^n


# Robin Condition

In [4]:
# Permeability tensor, scalar for simplicity
mu = 1
lmbda = 1

###
# This is where parameters can be modified to alter the convergence test.
# The remaining lines should 
np.random.seed(42)
base = 3
domain = np.array([1, 1])
basedim = np.array([base, base])
num_refs = 3
grid_type = 'cart'

# Analytical solution
x, y = sympy.symbols('x y')
ux = (0.5-y)**2 * sympy.sin(y) * sympy.cos(y)
uy = y * (y-1) * sympy.cosh(x)
ux_f = sympy.lambdify((x, y), ux, 'numpy')
uy_f = sympy.lambdify((x, y), uy, 'numpy')
dux_x = sympy.diff(ux, x)
dux_y = sympy.diff(ux, y)
duy_x = sympy.diff(uy, x)
duy_y = sympy.diff(uy, y)
divu = dux_x + duy_y

sxx = 2 * mu * dux_x + lmbda * divu
sxy = mu * (dux_y + duy_x)
syx = mu * (duy_x + dux_y)
syy = 2 * mu * duy_y + lmbda * divu

sxx_f = sympy.lambdify((x, y), sxx, 'numpy')
sxy_f = sympy.lambdify((x, y), sxy, 'numpy')
syx_f = sympy.lambdify((x, y), syx, 'numpy')
syy_f = sympy.lambdify((x, y), syy, 'numpy')

rhs_x = sympy.diff(sxx, x) + sympy.diff(syx, y)
rhs_y = sympy.diff(sxy, x) + sympy.diff(syy, y)
rhs_x_f = sympy.lambdify((x, y), rhs_x, 'numpy')
rhs_y_f = sympy.lambdify((x, y), rhs_y, 'numpy')

def run_convergence(grid_type, pert):
    u_err = []
    flux_err = []

    for g in setup_grids.grid_sequence(basedim, num_refs, grid_type, pert, domain=domain):
        # Reset the random seed for every grid realization.
        # This should make no difference for the convergence test, 
        # but it makes sure that we can run unit tests based on the values obtained
        # here.
        np.random.seed(42)
            
        xf = g.face_centers
        sx_ex_faces = np.vstack((sxx_f(xf[0], xf[1]), sxy_f(xf[0], xf[1])))
        sy_ex_faces = np.vstack((syx_f(xf[0], xf[1]), syy_f(xf[0], xf[1])))
        
        stress_x_ex = np.sum(g.face_normals[:2] * sx_ex_faces, axis=0)
        stress_y_ex = np.sum(g.face_normals[:2] * sy_ex_faces, axis=0)

        # Permeability tensor
        mu_c = mu * np.ones(g.num_cells)
        lmbda_c = lmbda * np.ones(g.num_cells)
        k = stiffness(2, mu_c, lmbda_c)
        robin_weight = 1.0
        # Set type of boundary conditions - Dirichlet
        n = g.nodes.max()
        # Set type of boundary conditions - Dirichlet
        top = np.ravel(np.argwhere(g.face_centers[1, :] > n - 1e-10))
        bot = np.ravel(np.argwhere(g.face_centers[1, :] < 1e-10))
        left = np.ravel(np.argwhere(g.face_centers[0, :] < 1e-10))
        right = np.ravel(np.argwhere(g.face_centers[0, :] > n - 1e-10))

        dir_faces = np.hstack((top, left))
        rob_faces = np.hstack((right, bot))
        bc_faces = np.hstack([dir_faces, rob_faces])
        bc_names = ['dir']*len(dir_faces) + ['rob'] * len(rob_faces)
        bound_cond = bc.BoundaryCondition(g, bc_faces, bc_names)
        
        # MPFA discretization, and system matrix
        stress, bound_stress = mpsa.mpsa(g, k, bound_cond,robin_weight=robin_weight)
        div = fvutils.vector_divergence(g)
        a = div * stress
        xf = g.face_centers
        
        rfi, _, sgn = sps.find(g.cell_faces[rob_faces,:])
        
        u_bound = np.zeros((g.dim, g.num_faces))
        u_bound[0, dir_faces] = ux_f(xf[0, dir_faces], xf[1, dir_faces])
        u_bound[1, dir_faces] = uy_f(xf[0, dir_faces], xf[1, dir_faces])
        
        # When setting the Neumann boundary condition we need to flip the 
        # sign of the faces with a normal pointing inwards as it is assumed
        # that the Neumann condition is the force from the boundary on to face
        u_bound[0, rob_faces[rfi]] = stress_x_ex[rob_faces[rfi]] * (sgn) + \
            robin_weight * ux_f(xf[0, rob_faces[rfi]], xf[1, rob_faces[rfi]]) * g.face_areas[rob_faces[rfi]]

        u_bound[1, rob_faces[rfi]] = stress_y_ex[rob_faces[rfi]] * (sgn) +\
            robin_weight * uy_f(xf[0, rob_faces[rfi]], xf[1, rob_faces[rfi]]) * g.face_areas[rob_faces[rfi]]
        # Right hand side - contribution from the solution and the boundary conditions
        xc = g.cell_centers
        rhs = np.vstack((rhs_x_f(xc[0], xc[1]), rhs_y_f(xc[0], xc[1]))) * g.cell_volumes
        b = rhs.ravel('F') - div * bound_stress * u_bound.ravel('F')

        # Solve system, derive fluxes
        u_num = spsolve(a, b)
        stress_num = stress * u_num + bound_stress * u_bound.ravel('F')

        ux_num = u_num[::2]
        uy_num = u_num[1::2]
        
        stress_x_num = stress_num[::2]
        stress_y_num = stress_num[1::2]
        # Exact solution
        ux_ex = ux_f(xc[0], xc[1])
        uy_ex = uy_f(xc[0], xc[1])
        u_ex = np.vstack((ux_ex, uy_ex))
        u_diff = np.vstack((ux_num - ux_ex, uy_num - uy_ex))
        
        stress_diff = np.vstack((stress_x_num - stress_x_ex, 
                                 stress_y_num - stress_y_ex))
        stress_ex = np.vstack((stress_x_ex, stress_y_ex))
        
        u_err.append(np.sqrt(np.sum(g.cell_volumes * u_diff**2)) /
                     np.sqrt(np.sum(g.cell_volumes * u_ex**2)))
        flux_err.append(np.sqrt(np.sum((g.face_areas ** g.dim) * stress_diff**2))/
                        np.sqrt(np.sum((g.face_areas ** g.dim) * stress_ex**2)))
                
        
    return u_err, flux_err

u_cart_nopert, f_cart_nopert = run_convergence('cart', 0)
u_cart_rate = np.array(u_cart_nopert)
u_cart_rate = u_cart_rate[:-1] / u_cart_rate[1:]
f_cart_rate = np.array(f_cart_nopert)
f_cart_rate = f_cart_rate[:-1] / f_cart_rate[1:]
print('Cartesian errors - no perturbations')
print(u_cart_nopert,'displacement error')
print(u_cart_rate, 'convergence rate u^n-1 / u^n\n')
print(f_cart_nopert,'stress error')
print(f_cart_rate, 'convergence rate f^n-1 / f^n\n')

u_triang_nopert, f_triang_nopert = run_convergence('triangular', 0)
u_triang_rate = np.array(u_triang_nopert)
u_triang_rate = u_triang_rate[:-1] / u_triang_rate[1:]
f_triang_rate = np.array(f_triang_nopert)
f_triang_rate = f_triang_rate[:-1] / f_triang_rate[1:]

print('Triangular errors - no perturbations')
print(u_triang_nopert,'displacement error')
print(u_triang_rate, 'convergence rate u^n-1 / u^n\n')
print(f_triang_nopert,'stress error')
print(f_triang_rate, 'convergence rate f^n-1 / f^n')

# RB: These values were hard-coded 11.09.2018.
assert np.abs(u_cart_nopert[2] - 0.0082926160732301) < 1e-10
assert np.abs(f_cart_nopert[2] - 0.004760957079948613) < 1e-10
assert np.abs(u_triang_nopert[2] - 0.006007054619672307) < 1e-10
assert np.abs(f_triang_nopert[2] - 0.0058474670379793795) < 1e-10


Cartesian errors - no perturbations
[0.13785825178140515, 0.033672908859893956, 0.0082926160732301] displacement error
[4.09404047 4.06058939] convergence rate u^n-1 / u^n

[0.04932864932955223, 0.01582468790884128, 0.004760957079948613] stress error
[3.11719571 3.32384595] convergence rate f^n-1 / f^n

Triangular errors - no perturbations
[0.11226477176063937, 0.025455746327683503, 0.006007054619672307] displacement error
[4.41019369 4.2376419 ] convergence rate u^n-1 / u^n

[0.044251086212033885, 0.016626084791879308, 0.0058474670379793795] stress error
[2.6615458  2.84329688] convergence rate f^n-1 / f^n


We note that the reduction rates are smallar than for the pure Dirichlet case - the asymptotic rates are 1 for displacement and 0.5 for stress. The reason for this is not understood - there are no obvious bugs in the code. Todo..

In [5]:
###
# This is where parameters can be modified to alter the convergence test.
# The remaining lines should 
np.random.seed(42)
base = 4
domain = np.array([1, 1])
basedim = np.array([base, base])
num_refs = 3
pert = 0.5

kappa_list = [1e-6, 1, 1e6]
### End of parameter definitions

# Permeability tensor, scalar for simplicity
mu = 1
mbda = 1

def chi(x, y):
    return np.logical_and(np.greater(x, 0.5), np.greater(y, 0.5))

# Analytical solution
x, y = sympy.symbols('x y')
ux = sympy.sin(2*pi * x) * sympy.sin(2 * pi * y)
uy = sympy.cos(pi * x) * (y-0.5)**2
ux_f = sympy.lambdify((x, y), ux, 'numpy')
uy_f = sympy.lambdify((x, y), uy, 'numpy')
dux_x = sympy.diff(ux, x)
dux_y = sympy.diff(ux, y)
duy_x = sympy.diff(uy, x)
duy_y = sympy.diff(uy, y)
divu = dux_x + duy_y

sxx = 2 * mu * dux_x + lmbda * divu
sxy = mu * (dux_y + duy_x)
syx = mu * (duy_x + dux_y)
syy = 2 * mu * duy_y + lmbda * divu

sxx_f = sympy.lambdify((x, y), sxx, 'numpy')
sxy_f = sympy.lambdify((x, y), sxy, 'numpy')
syx_f = sympy.lambdify((x, y), syx, 'numpy')
syy_f = sympy.lambdify((x, y), syy, 'numpy')

rhs_x = sympy.diff(sxx, x) + sympy.diff(syx, y)
rhs_y = sympy.diff(sxy, x) + sympy.diff(syy, y)
rhs_x_f = sympy.lambdify((x, y), rhs_x, 'numpy')
rhs_y_f = sympy.lambdify((x, y), rhs_y, 'numpy')


def run_convergence(grid_type, pert):
    u_err = np.zeros((num_refs, len(kappa_list)))
    flux_err = np.copy(u_err)
    
    for iter1, g in enumerate(setup_grids.grid_sequence_fixed_lines(basedim, num_refs, grid_type, pert, subdom_func=chi)):
        # Reset the random seed for every grid realization.
        # This should make no difference for the convergence test, 
        # but it makes sure that we can run unit tests based on the values obtained
        # here.
        np.random.seed(42)
        
        for iter2, kappa in enumerate(kappa_list):        
        # Permeability tensor
            char_func_cells = chi(g.cell_centers[0], g.cell_centers[1]) * 1.
            mat_vec = (1 - char_func_cells) + kappa * char_func_cells

            k = stiffness(2, mat_vec, mat_vec)

            # Set type of boundary conditions - Dirichlet
            bound_faces = g.get_all_boundary_faces()
            bound_cond = bc.BoundaryCondition(g, bound_faces, ['dir'] * bound_faces.size)

            # MPFA discretization, and system matrix
            stress, bound_stress = mpsa.mpsa(g, k, bound_cond)
            div = fvutils.vector_divergence(g)
            a = div * stress

            # Boundary conditions
            xf = g.face_centers
            char_func_bound = chi(xf[0, bound_faces], xf[1, bound_faces]) * 1
            u_bound = np.zeros((g.dim, g.num_faces))
            u_bound[0, bound_faces] = ux_f(xf[0, bound_faces], xf[1, bound_faces])\
                    / ((1 - char_func_bound) + kappa * char_func_bound)
            u_bound[1, bound_faces] = uy_f(xf[0, bound_faces], xf[1, bound_faces]) \
                    / ((1 - char_func_bound) + kappa * char_func_bound)

            # Right hand side - contribution from the solution and the boundary conditions
            xc = g.cell_centers
            rhs = np.vstack((rhs_x_f(xc[0], xc[1]), 
                             rhs_y_f(xc[0], xc[1]))) * g.cell_volumes
            b = rhs.ravel('F') - div * bound_stress * u_bound.ravel('F')

            # Solve system, derive fluxes
            u_num = spsolve(a, b)
            stress_num = stress * u_num + bound_stress * u_bound.ravel('F')

            ux_num = u_num[::2]
            uy_num = u_num[1::2]
            
            stress_x_num = stress_num[::2]
            stress_y_num = stress_num[1::2]
            # Exact solution
            ux_ex = ux_f(xc[0], xc[1])/ ((1 - char_func_cells) + kappa * char_func_cells)
            uy_ex = uy_f(xc[0], xc[1])/ ((1 - char_func_cells) + kappa * char_func_cells)
            u_ex = np.vstack((ux_ex, uy_ex))
            u_diff = np.vstack((ux_num - ux_ex, uy_num - uy_ex))

            sx_ex_faces = np.vstack((sxx_f(xf[0], xf[1]), sxy_f(xf[0], xf[1])))
            sy_ex_faces = np.vstack((syx_f(xf[0], xf[1]), syy_f(xf[0], xf[1])))

            stress_x_ex = np.sum(g.face_normals[:2] * sx_ex_faces, axis=0)
            stress_y_ex = np.sum(g.face_normals[:2] * sy_ex_faces, axis=0)
            stress_diff = np.vstack((stress_x_num - stress_x_ex, 
                                     stress_y_num - stress_y_ex))
            stress_ex = np.vstack((stress_x_ex, stress_y_ex))
            
            u_err[iter1, iter2] = np.sqrt(np.sum(g.cell_volumes * u_diff**2)) \
                        / np.sqrt(np.sum(g.cell_volumes * u_ex**2))
            flux_err[iter1, iter2] = np.sqrt(np.sum((g.face_areas ** g.dim) * stress_diff**2))\
                        / np.sqrt(np.sum((g.face_areas ** g.dim) * stress_ex**2))

    return u_err, flux_err

u_cart_nopert, f_cart_nopert = run_convergence('cart', 0)
print('Cartesian errors - no perturbations')
print(u_cart_nopert,'displacement error')
print(f_cart_nopert,'stress error')

u_cart_pert, f_cart_pert = run_convergence('cart', 0.5)
print('Cartesian errors - perturbation 0.5')
print(u_cart_pert,'displacement error')
print(f_cart_pert,'stress error')


u_triang_nopert, f_triang_nopert = run_convergence('triangular', 0)
print('Triangular errors - no perturbations')
print(u_triang_nopert,'displacement error')
print(f_triang_nopert,'stress error')


u_triang_pert, f_triang_pert = run_convergence('triangular', 0.5)
print('Triangular errors - perturbation 0.5')
print(u_triang_pert,'displacement error')
print(f_triang_pert,'stress error')

# EK: These values were hard-coded 12.06.2017.
assert np.abs(u_cart_nopert[2, 0] - 0.01980355  ) < 1e-7
assert np.abs(f_cart_nopert[2, 0] - 0.02181871   ) < 1e-7
assert np.abs(u_cart_pert[2, 0] - 0.02294892  ) < 1e-7
assert np.abs(f_cart_pert[2, 0] - 0.02941291  ) < 1e-7

# RB: These values were hard-coded 06.09.2018.
assert np.abs(u_triang_nopert[2, 0] - 0.01574973  ) < 1e-7
assert np.abs(f_triang_nopert[2, 0] - 0.01890709  ) < 1e-7
assert np.abs(u_triang_pert[2, 0] - 0.01911508  ) < 1e-7
assert np.abs(f_triang_pert[2, 0] - 0.02295011   ) < 1e-7

Cartesian errors - no perturbations
[[0.37388856 0.4014268  0.38285806]
 [0.08186136 0.09736873 0.08866018]
 [0.01980355 0.02491816 0.02207893]] displacement error
[[0.16987677 0.16287318 0.17095043]
 [0.06445937 0.05898811 0.06587345]
 [0.02181871 0.01941263 0.02240798]] stress error
Cartesian errors - perturbation 0.5
[[0.38707647 0.51439666 0.52211052]
 [0.10514942 0.11284306 0.10794662]
 [0.02294892 0.02818847 0.02665215]] displacement error
[[0.22785554 0.22643673 0.23802875]
 [0.07617105 0.06993615 0.07181565]
 [0.02941291 0.02754268 0.02920611]] stress error
Triangular errors - no perturbations
[[0.28239685 0.28600247 0.27724259]
 [0.06450559 0.06808808 0.0647828 ]
 [0.01574973 0.01710995 0.01599735]] displacement error
[[0.14821803 0.14406458 0.14628784]
 [0.05653494 0.05502727 0.05612567]
 [0.01890709 0.01837107 0.01901593]] stress error
Triangular errors - perturbation 0.5
[[0.34369963 0.45755484 0.47312797]
 [0.09035705 0.09202687 0.08932667]
 [0.01911508 0.02070007 0.020093

# Incompressible limit

In [6]:
# Permeability tensor, scalar for simplicity
mu = 1
lmbda = 1

###
# This is where parameters can be modified to alter the convergence test.
# The remaining lines should 
np.random.seed(42)
base = 4
domain = np.array([1, 1])
basedim = np.array([base, base])
num_refs = 4
grid_type = 'cart'

# Analytical solution
x, y = sympy.symbols('x y')
ux = sympy.sin(y) * (sympy.cos(x)-1)
uy = sympy.sin(x) * (1-sympy.cos(y))
ux_f = sympy.lambdify((x, y), ux, 'numpy')
uy_f = sympy.lambdify((x, y), uy, 'numpy')
dux_x = sympy.diff(ux, x)
dux_y = sympy.diff(ux, y)
duy_x = sympy.diff(uy, x)
duy_y = sympy.diff(uy, y)
divu = dux_x + duy_y

sxx = 2 * mu * dux_x + lmbda * divu
sxy = mu * (dux_y + duy_x)
syx = mu * (duy_x + dux_y)
syy = 2 * mu * duy_y + lmbda * divu

sxx_f = sympy.lambdify((x, y), sxx, 'numpy')
sxy_f = sympy.lambdify((x, y), sxy, 'numpy')
syx_f = sympy.lambdify((x, y), syx, 'numpy')
syy_f = sympy.lambdify((x, y), syy, 'numpy')

rhs_x = sympy.diff(sxx, x) + sympy.diff(syx, y)
rhs_y = sympy.diff(sxy, x) + sympy.diff(syy, y)
rhs_x_f = sympy.lambdify((x, y), rhs_x, 'numpy')
rhs_y_f = sympy.lambdify((x, y), rhs_y, 'numpy')

def run_convergence(grid_type, pert):
    u_err = np.zeros((num_refs, 3))
    flux_err = np.zeros((num_refs, 3))

    for iter1, g in enumerate(setup_grids.grid_sequence(basedim, num_refs, grid_type, pert, domain=domain)):
        for iter2, exponent in enumerate(range(2, 5)):
            # Reset the random seed for every grid realization.
            # This should make no difference for the convergence test, 
            # but it makes sure that we can run unit tests based on the values obtained
            # here.
            np.random.seed(42)

            lmbda = 10**exponent

            # Permeability tensor
            mu_c = mu * np.ones(g.num_cells)
            lmbda_c = lmbda * np.ones(g.num_cells)
            k = stiffness(2, mu_c, lmbda_c)

            # Set type of boundary conditions - Dirichlet
            bound_faces = g.get_all_boundary_faces()
            bound_cond = bc.BoundaryCondition(g, bound_faces, ['dir'] * bound_faces.size)

            # MPFA discretization, and system matrix
            stress, bound_stress = mpsa.mpsa(g, k, bound_cond)
            div = fvutils.vector_divergence(g)
            a = div * stress

            # Boundary conditions
            xf = g.face_centers
            u_bound = np.zeros((g.dim, g.num_faces))
            u_bound[0, bound_faces] = ux_f(xf[0, bound_faces], xf[1, bound_faces])
            u_bound[1, bound_faces] = uy_f(xf[0, bound_faces], xf[1, bound_faces])


            # Right hand side - contribution from the solution and the boundary conditions
            xc = g.cell_centers
            rhs = np.vstack((rhs_x_f(xc[0], xc[1]), rhs_y_f(xc[0], xc[1]))) * g.cell_volumes
            b = rhs.ravel('F') - div * bound_stress * u_bound.ravel('F')

            # Solve system, derive fluxes
            u_num = spsolve(a, b)
            stress_num = stress * u_num + bound_stress * u_bound.ravel('F')

            ux_num = u_num[::2]
            uy_num = u_num[1::2]

            stress_x_num = stress_num[::2]
            stress_y_num = stress_num[1::2]
            # Exact solution
            ux_ex = ux_f(xc[0], xc[1])
            uy_ex = uy_f(xc[0], xc[1])
            u_ex = np.vstack((ux_ex, uy_ex))
            u_diff = np.vstack((ux_num - ux_ex, uy_num - uy_ex))

            sx_ex_faces = np.vstack((sxx_f(xf[0], xf[1]), sxy_f(xf[0], xf[1])))
            sy_ex_faces = np.vstack((syx_f(xf[0], xf[1]), syy_f(xf[0], xf[1])))

            stress_x_ex = np.sum(g.face_normals[:2] * sx_ex_faces, axis=0)
            stress_y_ex = np.sum(g.face_normals[:2] * sy_ex_faces, axis=0)
            stress_diff = np.vstack((stress_x_num - stress_x_ex, 
                                     stress_y_num - stress_y_ex))
            stress_ex = np.vstack((stress_x_ex, stress_y_ex))
        
            u_err[iter1, iter2] = np.sqrt(np.sum(g.cell_volumes * u_diff**2)) \
                        / np.sqrt(np.sum(g.cell_volumes * u_ex**2))
            flux_err[iter1, iter2] = np.sqrt(np.sum((g.face_areas ** g.dim) * stress_diff**2))\
                        / np.sqrt(np.sum((g.face_areas ** g.dim) * stress_ex**2))

    return u_err, flux_err

u_cart_nopert, f_cart_nopert = run_convergence('cart', 0)
print('Cartesian errors - no perturbations')
print(u_cart_nopert,'displacement error')
print(f_cart_nopert,'stress error')

u_cart_pert, f_cart_pert = run_convergence('cart', 0.5)
print('Cartesian errors - perturbation 0.5')
print(u_cart_pert,'displacement error')
print(f_cart_pert,'stress error')


u_triang_nopert, f_triang_nopert = run_convergence('triangular', 0)
print('Triangular errors - no perturbations')
print(u_triang_nopert,'displacement error')
print(f_triang_nopert,'stress error')


u_triang_pert, f_triang_pert = run_convergence('triangular', 0.5)
print('Triangular errors - perturbation 0.5')
print(u_triang_pert,'displacement error')
print(f_triang_pert,'stress error')

# EK: These values were hard-bcoded 12.06.2017.
assert np.abs(u_cart_nopert[2, 0] -  0.00248737   ) < 1e-7
assert np.abs(f_cart_nopert[2, 0] -    0.00646923  ) < 1e-7
assert np.abs(u_cart_pert[2, 0] -  0.00270644   ) < 1e-7
assert np.abs(f_cart_pert[2, 0] -  0.01322056   ) < 1e-7

# RB: These values were hard-coded 06.09.2018.
assert np.abs(u_triang_nopert[2, 0] -  0.00108379   ) < 1e-7
assert np.abs(f_triang_nopert[2, 0] -   0.00390429  ) < 1e-7
assert np.abs(u_triang_pert[2, 0] -   0.00123134   ) < 1e-7
assert np.abs(f_triang_pert[2, 0] -   7.91132377e-03 ) < 1e-7

Cartesian errors - no perturbations
[[0.03697053 0.03753405 0.03759228]
 [0.00976093 0.00987151 0.00988294]
 [0.00248737 0.00251144 0.00251393]
 [0.00062543 0.00063108 0.00063166]] displacement error
[[0.05751235 0.05696182 0.05690496]
 [0.0198125  0.01970924 0.01969853]
 [0.00646923 0.00645496 0.00645348]
 [0.00209802 0.00209683 0.0020967 ]] stress error
Cartesian errors - perturbation 0.5
[[0.03956063 0.04032235 0.04040406]
 [0.01064916 0.01079559 0.01081118]
 [0.00270644 0.00277624 0.00279648]
 [0.0007012  0.00071505 0.00072281]] displacement error
[[0.10770594 0.54796429 5.20910705]
 [0.03973921 0.24607287 2.44840796]
 [0.01322056 0.02545624 0.19096982]
 [0.00524277 0.0151903  0.18131059]] stress error
Triangular errors - no perturbations
[[0.01757125 0.01776094 0.01778063]
 [0.00429797 0.00432499 0.00432781]
 [0.00108379 0.00108757 0.00108797]
 [0.00027397 0.00027454 0.0002746 ]] displacement error
[[0.033668   0.03356879 0.03355879]
 [0.01149681 0.0115022  0.01150278]
 [0.0039042

Note that on triangular grids, the convergence order for stress deteriorates for high Poisson's ratios. See Keilegavlen, Nordbotten IJNME 2017 for details.

# 3d homogeneous problem

This example also compares computational times for discretization and two linear solvers (direct and amg)

In [7]:
# Permeability tensor, scalar for simplicity
mu = 1
lmbda = 1

###
# This is where parameters can be modified to alter the convergence test.
# The remaining lines should 
np.random.seed(42)
base = 2
domain = np.array([1, 1, 1])
basedim = np.array([base, base, base])
num_refs = 3
grid_type = 'cart'

# Analytical solution. Essentially randomly made
x, y, z = sympy.symbols('x y z')
ux = sympy.sin(x) * sympy.cos(y) * (0.5 - z)**2
uy = sympy.sin(y) * x**2 * sympy.cos(z)
uz = sympy.cos(x) * sympy.sin(z) * y * (1-z)
ux_f = sympy.lambdify((x, y, z), ux, 'numpy')
uy_f = sympy.lambdify((x, y, z), uy, 'numpy')
uz_f = sympy.lambdify((x, y, z), uz, 'numpy')
dux_x = sympy.diff(ux, x)
dux_y = sympy.diff(ux, y)
dux_z = sympy.diff(ux, z)
duy_x = sympy.diff(uy, x)
duy_y = sympy.diff(uy, y)
duy_z = sympy.diff(uy, z)
duz_x = sympy.diff(uz, x)
duz_y = sympy.diff(uz, y)
duz_z = sympy.diff(uz, z)

divu = dux_x + duy_y + duz_z

sxx = 2 * mu * dux_x + lmbda * divu
sxy = mu * (dux_y + duy_x)
sxz = mu * (dux_z + duz_x) 
syx = mu * (duy_x + dux_y)
syy = 2 * mu * duy_y + lmbda * divu
syz = mu * (duy_z + duz_y)
szx = mu * (duz_x + dux_z)
szy = mu * (duy_z + duz_y)
szz = 2 * mu * duz_z + lmbda * divu

sxx_f = sympy.lambdify((x, y, z), sxx, 'numpy')
sxy_f = sympy.lambdify((x, y, z), sxy, 'numpy')
sxz_f = sympy.lambdify((x, y, z), sxz, 'numpy')
syx_f = sympy.lambdify((x, y, z), syx, 'numpy')
syy_f = sympy.lambdify((x, y, z), syy, 'numpy')
syz_f = sympy.lambdify((x, y, z), syz, 'numpy')
szx_f = sympy.lambdify((x, y, z), szx, 'numpy')
szy_f = sympy.lambdify((x, y, z), szy, 'numpy')
szz_f = sympy.lambdify((x, y, z), szz, 'numpy')

rhs_x = sympy.diff(sxx, x) + sympy.diff(syx, y) + sympy.diff(szx, z)
rhs_y = sympy.diff(sxy, x) + sympy.diff(syy, y) + sympy.diff(szy, z)
rhs_z = sympy.diff(sxz, x) + sympy.diff(syz, y) + sympy.diff(szz, z)
rhs_x_f = sympy.lambdify((x, y, z), rhs_x, 'numpy')
rhs_y_f = sympy.lambdify((x, y, z), rhs_y, 'numpy')
rhs_z_f = sympy.lambdify((x, y, z), rhs_z, 'numpy')


def run_convergence(grid_type, pert):
    u_err = []
    flux_err = []

    for g in setup_grids.grid_sequence(basedim, num_refs, grid_type, pert, domain=domain):
        # Reset the random seed for every grid realization.
        # This should make no difference for the convergence test, 
        # but it makes sure that we can run unit tests based on the values obtained
        # here.
        np.random.seed(42)
            
        # Permeability tensor
        mu_c = mu * np.ones(g.num_cells)
        lmbda_c = lmbda * np.ones(g.num_cells)
        k = stiffness(g.dim, mu_c, lmbda_c)

        # Set type of boundary conditions - Dirichlet
        bound_faces = g.get_boundary_faces()
        bound_cond = bc.BoundaryCondition(g, bound_faces, ['dir'] * bound_faces.size)
        
        # MPFA discretization, and system matrix
        tm = time()
        stress, bound_stress = mpsa.mpsa(g, k, bound_cond)
        print('Time for discretization ' + str(time() - tm))
        div = fvutils.vector_divergence(g)
        a = div * stress
        a.tocsr()
        
        # Boundary conditions
        xf = g.face_centers
        u_bound = np.zeros((g.dim, g.num_faces))
        u_bound[0, bound_faces] = ux_f(xf[0, bound_faces], xf[1, bound_faces], xf[2, bound_faces])
        u_bound[1, bound_faces] = uy_f(xf[0, bound_faces], xf[1, bound_faces], xf[2, bound_faces])
        u_bound[2, bound_faces] = uz_f(xf[0, bound_faces], xf[1, bound_faces], xf[2, bound_faces])
        
        # Right hand side - contribution from the solution and the boundary conditions
        xc = g.cell_centers
        rhs = np.vstack((rhs_x_f(xc[0], xc[1], xc[2]), 
                         rhs_y_f(xc[0], xc[1], xc[2]),
                         rhs_z_f(xc[0], xc[1], xc[2]))) * g.cell_volumes
        b = rhs.ravel('F') - div * bound_stress * u_bound.ravel('F')

        # Solve system, derive fluxes
        tm = time()
        smooth = smooth=('energy', {'krylov': 'gmres', 'degree': 2})
        
        null_space = np.zeros((g.dim * g.num_cells, 6))
        null_space[0::g.dim, 0] = 1
        null_space[1::g.dim, 1] = 1
        null_space[2::g.dim, 2] = 1
        # Rotations
        null_space[0::g.dim, 3] = 1
        null_space[1::g.dim, 3] = -1
        null_space[1::g.dim, 4] = 1
        null_space[2::g.dim, 4] = -1
        null_space[2::g.dim, 5] = 1
        null_space[0::g.dim, 5] = -1

        res = []
        a = a.tocsr()
        ml = pyamg.smoothed_aggregation_solver(a, null_space, smooth=smooth, symmetry='nonsymmetric')
        u_num = ml.solve(b, residuals=res, tol=1e-12)
        stress_num = stress * u_num + bound_stress * u_bound.ravel('F')
        print('Time for AMG ' + str(time() - tm))
        ux_num = u_num[::g.dim]
        uy_num = u_num[1::g.dim]
        uz_num = u_num[2::g.dim]
        
        stress_x_num = stress_num[::g.dim]
        stress_y_num = stress_num[1::g.dim]
        stress_z_num = stress_num[2::g.dim]
        # Exact solution
        ux_ex = ux_f(xc[0], xc[1], xc[2])
        uy_ex = uy_f(xc[0], xc[1], xc[2])
        uz_ex = uz_f(xc[0], xc[1], xc[2])
        u_ex = np.vstack((ux_ex, uy_ex, uz_ex))
        u_diff = np.vstack((ux_num - ux_ex, uy_num - uy_ex))
        
        sx_ex_faces = np.vstack((sxx_f(xf[0], xf[1], xf[2]),
                                 sxy_f(xf[0], xf[1], xf[2]),
                                 sxz_f(xf[0], xf[1], xf[2])))
        
        sy_ex_faces = np.vstack((syx_f(xf[0], xf[1], xf[2]),
                                 syy_f(xf[0], xf[1], xf[2]),
                                 syz_f(xf[0], xf[1], xf[2])))
        
        sz_ex_faces = np.vstack((szx_f(xf[0], xf[1], xf[2]),
                                 szy_f(xf[0], xf[1], xf[2]),
                                 szz_f(xf[0], xf[1], xf[2])))

        stress_x_ex = np.sum(g.face_normals[:g.dim] * sx_ex_faces, axis=0)
        stress_y_ex = np.sum(g.face_normals[:g.dim] * sy_ex_faces, axis=0)
        stress_z_ex = np.sum(g.face_normals[:g.dim] * sz_ex_faces, axis=0)
        stress_diff = np.vstack((stress_x_num - stress_x_ex, 
                                 stress_y_num - stress_y_ex,
                                 stress_z_num - stress_z_ex))
        stress_ex = np.vstack((stress_x_ex, stress_y_ex, stress_z_ex))
        
        u_err.append(np.sqrt(np.sum(g.cell_volumes * u_diff**2)) /
                     np.sqrt(np.sum(g.cell_volumes * u_ex**2)))
        flux_err.append(np.sqrt(np.sum((g.face_areas ** g.dim) * stress_diff**2))/
                        np.sqrt(np.sum((g.face_areas ** g.dim) * stress_ex**2)))
    return u_err, flux_err


grids = ['cart', 'triangular']


u_cart_nopert, f_cart_nopert = run_convergence('cart', 0)
print('Cartesian errors - no perturbations')
print(u_cart_nopert,'displacement error')
print(f_cart_nopert,'stress error')

u_cart_pert, f_cart_pert = run_convergence('cart', 0.5)
print('Cartesian errors - perturbation 0.5')
print(u_cart_pert,'displacement error')
print(f_cart_pert,'stress error')


u_triang_nopert, f_triang_nopert = run_convergence('tetrahedral', 0)
print('Triangular errors - no perturbations')
print(u_triang_nopert,'displacement error')
print(f_triang_nopert,'stress error')


u_triang_pert, f_triang_pert = run_convergence('tetrahedral', 0.3)
print('Triangular errors - perturbation 0.5')
print(u_triang_pert,'displacement error')
print(f_triang_pert,'stress error')

# EK: These values were hard-coded 16.06.2017.
assert np.abs(u_cart_nopert[2] - 0.0096234771484497109) < 1e-10
assert np.abs(f_cart_nopert[2] - 0.018777567804377917) < 1e-10
assert np.abs(u_cart_pert[2] - 0.0097853910627935265) < 1e-10
assert np.abs(f_cart_pert[2] - 0.024831033744125156) < 1e-10

# RB: These values were hard-coded 06.09.2018.
assert np.abs(u_triang_nopert[2] - 0.004112646550453208) < 1e-10
assert np.abs(f_triang_nopert[2] - 0.01608810670167512) < 1e-10
assert np.abs(u_triang_pert[2] - 0.004336430438721095) < 1e-10
assert np.abs(f_triang_pert[2] - 0.017041050867287796) < 1e-10

Time for discretization 1.08636474609375
Time for AMG 0.020662784576416016
Time for discretization 1.6143503189086914
Time for AMG 0.07893586158752441
Time for discretization 1.8830769062042236
Time for AMG 0.4144134521484375
Cartesian errors - no perturbations
[0.14582494480280667, 0.036685508143867125, 0.009623477148373078] displacement error
[0.14173578960074407, 0.05453461058511372, 0.018777567804334296] stress error
Time for discretization 1.1395857334136963
Time for AMG 0.010153055191040039
Time for discretization 1.394442081451416
Time for AMG 0.0783224105834961
Time for discretization 1.727994680404663
Time for AMG 0.37769436836242676
Cartesian errors - perturbation 0.5
[0.1823425575505196, 0.03669658584037131, 0.009785391062793553] displacement error
[0.15394769153699012, 0.06655533666156926, 0.024831033744125167] stress error
Time for discretization 1.5092995166778564
Time for AMG 0.04783058166503906
Time for discretization 2.5991227626800537
Time for AMG 0.35640907287597656


In [8]:
pyamg.smoothed_aggregation_solver?